=== MarcWeber/vxml/dtds/test.dtd
<!ELEMENT a EMPTY>
<!ATTLIST a
  id          ID             #IMPLIED
  >
<!ELEMENT b EMPTY>
<!ATTLIST b
  id          ID             #IMPLIED
  >
<!ELEMENT c EMPTY>
<!ATTLIST c
  id          ID             #IMPLIED
  >
<!ELEMENT d EMPTY>
<!ELEMENT e EMPTY>
<!ELEMENT f EMPTY>


<!ELEMENT choice ((a | b )? | c+)>
<!ATTLIST choice
  id          ID             #IMPLIED
  >


<!ELEMENT sequence (a, b, c)>
<!ELEMENT testcase1 (a, b?, c)>
<!ELEMENT testcase2 ((a?, b)| (c?, d))>

<!ELEMENT testcase3 ( ( (a?, d)
                      | (b?)
                      )
                    , c )
                    >

<!ELEMENT root ((
                choice 
                | sequence
                | testcase1
                | testcase2
                | testcase3
                | a
                )+)>
<!ATTLIST root
  id          CDATA             #IMPLIED
  >

=== MarcWeber/vxml/test/test_dtd.xml
<!DOCTYPE root PUBLIC "vxml-test" "../dtds/test.dtd">
<root id="abc">
  <!-- sequnce 1 -->
  <testcase1>
    <a></a><b></b><c></c>
  </testcase1>
  <!-- sequnce 2 (b may be omitted) -->
  <testcase1>
    <a></a><c></c>
  </testcase1>

  <!-- choice 1 -->
  <choice></choice>
  <choice></choice>
  <choice><a></a></choice>
  <choice><b></b></choice>
  <choice><c></c><c></c><c></c></choice> <!-- c many times -->

  <!--testcase 2 -->
  <testcase2> <b/>     </testcase2>
  <testcase2> <a/><b/> </testcase2>
  <testcase2> <d/>     </testcase2>
  <testcase2> <c/><d/> </testcase2>

  <!-- testcase 3 -->
  <testcase3> <c/> </testcase3>
  <testcase3> <b/><c/> </testcase3>
  <testcase3> <d/><c/> </testcase3>
  <testcase3> <a/><d/><c/> </testcase3>

</root>
